name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.0
    steps:

      - name: Install dependencies
        uses: actions/checkout@v2

      - name: Compile 
        run: |
          make

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: OSDSYS-LAUNCHER
          path: |
             *.ELF

      - name: Create release
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest build"
          files: |
              *.ELF
